version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: checkout submodules
          command: make git-submodule
      - run:
          name: docker build
          command: util/docker_build.sh planck/rev6:nakatsuchi
      - store_artifacts:
          path: .build/planck_rev6_nakatsuchi.hex

