version: 2
jobs:
  build:
    docker:
      - image: edasque/qmk_firmware
    steps:
      - run: |
        echo "deb http://security.debian.org/debian-security jessie/updates main" >> /etc/apt/sources.list
        apt-get update
        apt-get install -y ca-certificates
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - run: |
          make clean
          make keyboard=planck/rev6 keymap=nakatsuchi
      - store_artifacts:
          path: .build/planck_rev6_nakatsuchi.hex

