version: 2
jobs:
  build:
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - run: |
          make clean
          make keyboard=planck/rev6 keymap=nakatsuchi
      - store_artifacts:
          path: .build/planck_rev6_nakatsuchi.hex

