version: 2
jobs:
  build:
    docker:
      - image: edasque/qmk_firmware
    steps:
      - checkout
        post:
          - git submodule sync
          - git submodule update --init
      - run:
          name: build keymap
          command: |
            make clean
            make keyboard=planck/rev6 keymap=nakatsuchi
      - run:
          name: docker build
          command: util/docker_build.sh planck/rev6:nakatsuchi
      - store_artifacts:
          path: .build/planck_rev6_nakatsuchi.hex

